### ISSUE TITLE
broken, probably by changes in lightgallery

### ISSUE THREAD

**Issue by ghost** [timmydoza/express-photo-gallery#3]
I get a blank page in the browser, and 

    lightgallery.min.js:4 Uncaught When using dynamic mode, you must also define dynamicEl as an Array.

in the console. This is with node.js and browsers at their current versions in Debian testing. Please let me know what other information you need.

**Comment by timmydoza** [comment]
Thanks for the comment.  The error you reference occurs when there are no images in the path provided to express-photo-gallery.

I just added support for more image formats.  Additionally, express-photo-gallery is now case insensitive with respect to file extensions.  Previously, it only included files with an extension of lowercase 'jpg', so if your image folder had only files with 'JPG' extensions (for instance), you would see that error.  

Let me know if it still isn't fixed.  Thanks.
